# Generated by Django 2.2 on 2021-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='없음', max_length=120),
        ),
        migrations.AddField(
            model_name='menu',
            name='img_path',
            field=models.CharField(default='없음', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='익명', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name_eng',
            field=models.CharField(default='name', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
